export default [
    {
        manufacturer: "Porsche",
        name: "Porsche GT3",
        tagline: "Starting at $161,100",
        maxPower: "502 hp",
        maxTorque: "346 lb-ft",
        trackSpeed: "197 mph",
        quote: "A 9000-rpm love letter to a dying breed",
        url: "https://www.6speedonline.com/forums/gt3-gt2-12/",
        image: require("../../assets/images/pgt3.jpeg"),
    },
    {
        manufacturer: "Porsche",
        name: " 911 Turbo S",
        tagline: "Starting at $63,100",
        maxPower: "502 hp",
        maxTorque: "346 lb-ft",
        trackSpeed: "197 mph",
        quote: "The Fastest Porsche Yet",
        url: "https://rennlist.com/forums/992-turbo-and-turbo-s-258/",
        image: require("../../assets/images/turbos.jpeg"),
    },
    {
        manufacturer: "BMW",
        name: "BMW E92 M3",
        tagline: " Starting at $40,000",
        maxPower: "420 hp",
        maxTorque: "400 lb-ft",
        trackSpeed: "160 mph",
        quote: "The Last True M Car",
        url: "https://www.m3post.com/forums/forumdisplay.php?f=284",
        image: require("../../assets/images/e92m3.jpeg"),
    },
    {
        manufacturer: "BMW",
        name: "BMW M4",
        tagline: "Starting at $60,100",
        maxPower: "473 hp",
        maxTorque: "406 lb-ft",
        trackSpeed: "155 mph",
        quote: "A Two-Door That Roars",
        url: "https://f80.bimmerpost.com/forums/forumdisplay.php?f=625",
        image: require("../../assets/images/m4.jpeg"),
    },
    {
        manufacturer: "Ford",
        name: "Mustang GT350",
        tagline: "Starting at $60,100",
        maxPower: "526 hp",
        maxTorque: "429 lb-ft",
        trackSpeed: "172 mph",
        quote: "The Modern Collectible",
        url: "https://www.gt350.org/forums/cars-for-sale.37/",
        image: require("../../assets/images/gt350.jpeg"),
    },
    {
        manufacturer: "Chevrolet",
        name: "Camaro 2SS",
        tagline: "Starting at $63,100",
        maxPower: "455 hp",
        maxTorque: "455 lb-ft",
        trackSpeed: "165 mph",
        quote: "The best all-around Camaro ever",
        url: "https://www.camaro6.com/forums/forumdisplay.php?f=279",
        image: require("../../assets/images/camaro.jpeg"),
    },
    {
        manufacturer: "Chevrolet",
        name: "Corvette Z06",
        tagline: "Starting at $60,100",
        maxPower: "670 hp",
        maxTorque: "460 lb-ft",
        trackSpeed: "175 mph",
        quote: "The pinnacle of American performance",
        url: "https://www.corvetteforum.com/forums/c6-corvettes-for-sale-98/",
        image: require("../../assets/images/Z06.jpeg"),
    },
];
